Add GitHub issue templates
realm/realm-kotlin pull request #1328
Opened 2023-03-29 07:24 UTC by rorbech

This adds a menu and forms for creating new issues. Just grabbed the Java templates and updated the link to the forum to show the kotlin issues instead.

2023-03-29 07:34 UTC, bmunkholm requested changes
This doesn't look like the latest one from Java? Did you use an older version?
All dropdown options has to be exactly the same - character-by-charater.

2023-03-29 08:09 UTC, rorbech commented
> This doesn't look like the latest one from Java? Did you use an older version? All dropdown options has to be exactly the same - character-by-charater.

Argh, yes. I copied it from the `transformer-api` branch but that is spun from the `releases` branch and not `main` as I recalled. I have updated it from the latest `main` version. Thanks.

2023-03-29 08:11 UTC, bmunkholm commented on .github/ISSUE_TEMPLATE/bug.yml
> +    id: java-build-environment
```suggestion
    id: kotlin-build-environment
```

2023-03-29 08:13 UTC, bmunkholm approved these changes

2023-03-30 12:01 UTC, cmelchior approved these changes

2023-03-31 12:19 UTC, merged