Disable symbol  lookup for source set not using Realm
realm/realm-kotlin pull request #593
Opened 2021-11-24 13:35 UTC by nhachicha

Fixes https://github.com/realm/realm-kotlin/issues/544

2021-11-24 14:05 UTC, cmelchior approved these changes
Missing a changelog entry. Otherwise looks fine to me 🚀

2021-11-26 12:18 UTC, rorbech requested changes
I foresee that we end up reintroducing this issue again at some point if we don't address it generically. Maybe we can just add a test case that safeguards this, but wouldn't it somehow be possible to avoid triggering any internals of the sub compiler plugin at all. It seems a bit of waste that we actually have the registrar and register extensions, etc. if there is no need. I have absolutely no idea on how/if this is possible, but would be the preferred solution ... and as said alternatively a test to ensure that we don't introduce it again.

2021-11-29 14:24 UTC, nhachicha commented
@rorbech I updated the minimal Android project to include a JVM target not using the Realm dependencies as a way to catch similar issues.

2021-11-29 14:28 UTC, rorbech approved these changes

2021-11-29 14:30 UTC, merged